In [1]:
import numpy as np

#### 1. Write a NumPy program to find the dot product of two arrays of different dimensions.

In [3]:
nums1=np.array([[1,2],[3,4],[5,6]])
nums2=np.array([7,8])

In [6]:
np.dot(nums1,nums2)

array([23, 53, 83])

##### 2. Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally.

In [9]:
m=np.identity(3)

In [12]:
np.vstack((m,m))

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
np.hstack((m,m))

array([[1., 0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 1.]])

#### 3. Write a NumPy program to create a 4x4 array with random values and find the sum of each row.

In [18]:
mat=np.random.randint(1,100,16).reshape(4,4)

In [19]:
np.sum(mat,axis=1)

array([257, 203, 108, 168])

#### 4. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.

In [21]:
mat=np.random.randint(1,100,(4,4))

In [23]:
m=np.mean(mat,axis=1)

In [24]:
mat-m

array([[ 55.25, -31.25, -23.75, -22.  ],
       [ 29.25, -18.25,   7.25, -38.  ],
       [ 21.25,  42.75, -11.75,   6.  ],
       [-22.75, -11.25,  -2.75,  20.  ]])

#### 5. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element.

In [28]:
mat=np.random.randint(1,200,(3,3))

In [29]:
mat-np.mean(mat,axis=0)

array([[ 48.33333333, -41.66666667, -13.        ],
       [ 11.33333333,  47.33333333,  69.        ],
       [-59.66666667,  -5.66666667, -56.        ]])

#### 6. Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.

In [42]:
mat=np.random.randint(1,2000,(5,5))
mat/np.linalg.norm(mat,axis=1,keepdims=True)


array([[0.89114427, 0.02000431, 0.33912064, 0.24576721, 0.17337067],
       [0.31976157, 0.29267133, 0.63323434, 0.10062089, 0.63323434],
       [0.20172306, 0.03391804, 0.65551068, 0.64372863, 0.33775224],
       [0.22611908, 0.88481381, 0.23371597, 0.33068799, 0.04468757],
       [0.05878958, 0.19004074, 0.28483324, 0.76335308, 0.54460115]])

#### 8. Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.

In [45]:
mat=np.random.rand(3,3,3)
np.sum(mat,axis=2)

array([[2.05163365, 1.62567888, 1.77644367],
       [1.72262257, 1.53121644, 0.92905226],
       [1.72687762, 2.2754087 , 2.1052793 ]])

9. Write a NumPy program to create a 5x5 array with random values and sort each row.

10.Write a NumPy program to create a 5x5 array with random values and sort each column.

In [46]:
mat=np.random.rand(5,5)

In [47]:
np.sort(mat,axis=1)


array([[5.45754932e-02, 5.94286547e-02, 2.97669355e-01, 5.31717617e-01,
        5.73317956e-01],
       [2.25120633e-01, 3.81255298e-01, 6.17894749e-01, 6.41855445e-01,
        8.80976585e-01],
       [2.42623937e-01, 4.85142348e-01, 5.17669674e-01, 5.97963935e-01,
        8.03436575e-01],
       [8.67352373e-04, 2.65013129e-01, 3.56008917e-01, 5.78619987e-01,
        5.83263324e-01],
       [7.90340989e-02, 5.32284406e-01, 7.59498268e-01, 8.36027268e-01,
        9.13440841e-01]])

In [48]:
np.sort(mat,axis=0)

array([[8.67352373e-04, 5.45754932e-02, 2.25120633e-01, 2.42623937e-01,
        5.94286547e-02],
       [7.90340989e-02, 3.56008917e-01, 2.65013129e-01, 2.97669355e-01,
        5.17669674e-01],
       [5.31717617e-01, 3.81255298e-01, 4.85142348e-01, 5.32284406e-01,
        5.83263324e-01],
       [8.03436575e-01, 5.97963935e-01, 5.73317956e-01, 5.78619987e-01,
        6.17894749e-01],
       [8.80976585e-01, 8.36027268e-01, 9.13440841e-01, 6.41855445e-01,
        7.59498268e-01]])

#### 11. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.

#### 12. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.

In [60]:
mat=np.random.rand(5,5)

In [64]:
np.partition(mat,-2,axis=1)[:,-2]

array([0.51041263, 0.77499909, 0.52783602, 0.72610449, 0.70010053])

In [66]:
#for columns
np.partition(mat,-2,axis=0)[-2,:]

array([0.77499909, 0.70010053, 0.73660155, 0.52783602, 0.72610449])

#### 13. Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0.

####  14. Write a NumPy program to create a 5x5 array with random values and replace the minimum value with 0.

In [67]:
mat=np.random.rand(5,5)

In [73]:
max=np.max(mat)
mat[mat==max]=0

In [78]:
min_val=np.min(mat)
mat[mat==min_val]=0

#### 15. Write a NumPy program to create a 5x5 array with random values and calculate the exponential of each element.

In [82]:
mat=np.random.rand(5,5)

In [83]:
np.exp(mat)

array([[1.11034817, 1.06396906, 1.38069844, 2.26824132, 2.316276  ],
       [2.20217936, 1.36053642, 1.55355702, 1.19732934, 1.10936563],
       [2.19101676, 1.54011891, 1.09258105, 1.86596307, 1.66916333],
       [1.39138166, 1.65653541, 1.78905674, 1.58018316, 1.73345879],
       [1.44760474, 1.23034926, 1.63117927, 2.13935464, 1.1996812 ]])