In [1]:
import numpy as np

#### 1. Write a NumPy program to sort a given array of shape 2 along the first axis, last axis and on flattened array.

In [7]:
mat=np.array([[2,1],[4,3]])

In [5]:
np.sort(mat,axis=1)

array([[1, 2],
       [3, 4]])

In [15]:
np.sort(mat,axis=0)

array([[1, 2],
       [3, 4]])

In [13]:
np.sort(mat,axis=None)

array([1, 2, 3, 4])

array([[1, 2],
       [3, 4]])

#### 2. Write a NumPy program to create a structured array from given student name, height, class and their data types. Now sort the array on height.

In [16]:
data_type = [('name', 'S15'), ('class', int), ('height', float)]
students_details = [('James', 5, 48.5), ('Nail', 6, 52.5),('Paul', 5, 42.10), ('Pit', 5, 40.11)]

In [18]:
students=np.array(students_details,dtype=data_type)

In [21]:
np.sort(students,order='height')

array([(b'Pit', 5, 40.11), (b'Paul', 5, 42.1 ), (b'James', 5, 48.5 ),
       (b'Nail', 6, 52.5 )],
      dtype=[('name', 'S15'), ('class', '<i4'), ('height', '<f8')])